export const PLANS = [
    {
        id: 'free',
        name: 'Starter',
        price: { monthly: '$0', yearly: '$0' },
        checkoutUrl: { monthly: null, yearly: null },
        description: 'Perfect for testing and personal side projects',
        features: [
            '5 Smart Links / Mo',
            'Basic Click Analytics',
            'Elite Bio Page Builder',
            'Static Branding QR Codes',
            'Standard SSL Protection',
        ],
        cta: 'Get Started Free',
        popular: false,
        theme: {
            accent: 'from-blue-500 to-indigo-500',
            border: 'border-white/10',
            bg: 'bg-white/5',
            text: 'text-white',
            glow: 'shadow-blue-500/10'
        },
        isTrial: false,
        trialAvailable: false,
    },
    {
        id: 'pro',
        name: 'Pro Creator',
        price: { monthly: '$9', yearly: '$7' },
        checkoutUrl: {
            monthly: import.meta.env.VITE_PRO_MONTHLY_CHECKOUT_URL || '',
            yearly: import.meta.env.VITE_PRO_YEARLY_CHECKOUT_URL || '',
        },
        description: 'Maximize ROI with Profit Intelligence',
        features: [
            'Everything in Starter',
            'Profit Intelligence Dashboard',
            'Auto-Shield (Bot Protection)',
            'Revenue Recovery (Language)',
            'Verified Custom Domains',
            'Advanced Device Targeting',
            'Geotargeting (Country Level)',
            'Unlimited Smart Links',
        ],
        cta: 'Unlock Pro Power',
        popular: true,
        theme: {
            accent: 'from-indigo-500 via-blue-600 to-indigo-500',
            border: 'border-blue-500/30',
            bg: 'bg-blue-600/10',
            text: 'text-white',
            glow: 'shadow-blue-600/30'
        },
        isTrial: false,
        trialAvailable: false,
    },
    {
        id: 'business',
        name: 'Business Elite',
        price: { monthly: '$19', yearly: '$15' },
        checkoutUrl: {
            monthly: import.meta.env.VITE_BUSINESS_MONTHLY_CHECKOUT_URL || '',
            yearly: import.meta.env.VITE_BUSINESS_YEARLY_CHECKOUT_URL || '',
        },
        description: 'AI-Powered engine for professional agencies',
        features: [
            'Everything in Pro Creator',
            'AI-Powered Auto-A/B Testing',
            'Full Conversion & ROI Tracking',
            'Advanced Ad-Fraud Protection',
            'Targeting by City & ISP',
            'Premium Retargeting Pixels',
            'Personal Account Manager',
        ],
        cta: 'Upgrade to Elite',
        popular: false,
        theme: {
            accent: 'from-purple-500 via-indigo-600 to-purple-500',
            border: 'border-purple-500/20',
            bg: 'bg-purple-500/5',
            text: 'text-white',
            glow: 'shadow-purple-500/10'
        },
        isTrial: false,
        trialAvailable: false,
    },
];