export const PLANS = [
    {
        id: 'starter',
        name: 'Starter',
        price: { monthly: '$29', yearly: '$24' },
        checkoutUrl: {
            monthly: import.meta.env.VITE_STARTER_MONTHLY_CHECKOUT_URL || '',
            yearly: import.meta.env.VITE_STARTER_YEARLY_CHECKOUT_URL || '',
        },
        description: 'Launch your first campaigns with confidence.',
        features: [
            '15 Smart Links / Month',
            'Real-Time Click Analytics',
            'Link Cloaking & Protection',
            'Bio Page Builder',
            'Basic Bot Detection',
            'QR Code Generation',
            'Standard SSL Protection',
        ],
        cta: 'Start 14-Day Free Trial',
        popular: false,
        theme: {
            accent: 'from-blue-500 to-indigo-500',
            border: 'border-white/10',
            bg: 'bg-white/5',
            text: 'text-white',
            glow: 'shadow-blue-500/10'
        },
        isTrial: true,
        trialAvailable: true,
    },
    {
        id: 'pro',
        name: 'Pro Affiliate',
        price: { monthly: '$79', yearly: '$65' },
        checkoutUrl: {
            monthly: import.meta.env.VITE_PRO_MONTHLY_CHECKOUT_URL || '',
            yearly: import.meta.env.VITE_PRO_YEARLY_CHECKOUT_URL || '',
        },
        description: 'Everything a serious affiliate needs to scale. 45% cheaper than Voluum.',
        features: [
            'Unlimited Smart Links',
            'Geo-Targeting (Country Level)',
            'Device & OS Targeting',
            'A/B Split Testing',
            'Auto-Shield Bot Protection',
            'Retargeting Pixels (FB, Google, TikTok)',
            'Verified Custom Domains',
            'Advanced Click Analytics',
            'Language-Based Routing',
        ],
        cta: 'Start Scaling — $79/mo',
        popular: true,
        theme: {
            accent: 'from-indigo-500 via-blue-600 to-indigo-500',
            border: 'border-blue-500/30',
            bg: 'bg-blue-600/10',
            text: 'text-white',
            glow: 'shadow-blue-600/30'
        },
        isTrial: false,
        trialAvailable: false,
    },
    {
        id: 'business',
        name: 'Agency Elite',
        price: { monthly: '$199', yearly: '$169' },
        checkoutUrl: {
            monthly: import.meta.env.VITE_BUSINESS_MONTHLY_CHECKOUT_URL || '',
            yearly: import.meta.env.VITE_BUSINESS_YEARLY_CHECKOUT_URL || '',
        },
        description: 'Full conversion intelligence for agencies and super-affiliates.',
        features: [
            'Everything in Pro Affiliate',
            'Sub-accounts & Team Management',
            'AI-Powered A/B Auto-Optimization',
            'Full Conversion & ROI Tracking',
            'Advanced Ad-Fraud Detection',
            'City & ISP-Level Targeting',
            'Sub-ID & Postback Tracking',
            'Premium Retargeting Pixels',
            'Dedicated Account Manager',
            'API Access',
        ],
        cta: 'Go Elite — $199/mo',
        popular: false,
        theme: {
            accent: 'from-purple-500 via-indigo-600 to-purple-500',
            border: 'border-purple-500/20',
            bg: 'bg-purple-500/5',
            text: 'text-white',
            glow: 'shadow-purple-500/10'
        },
        isTrial: false,
        trialAvailable: false,
    },
];
